name: Build

on:
  push:
    branches-ignore: [master]
  pull_request:
    branches: [master]
  workflow_dispatch:

jobs:
  build:
    name: Build and Deploy to Vercel Preview
    runs-on: ubuntu-latest
    environment:
      name: preview
      url: ${{ steps.deployment.outputs.DEPLOYMENT_URL }}
    env:
      TURBO_TOKEN: ${{ secrets.TURBO_TOKEN }}
      TURBO_TEAM: ${{ github.actor }}
      VERCEL_PROJECT_ID: ${{ secrets.VERCEL_PROJECT_ID }}
      VERCEL_ORG_ID: ${{ secrets.VERCEL_ORG_ID }}
    steps:
      - uses: actions/checkout@v4.2.2
      - name: Set up pnpm
        uses: pnpm/action-setup@v4.1.0
      - name: Set up Node.js
        uses: actions/setup-node@v4.3.0
        with:
          node-version-file: package.json
          cache: "pnpm"
      - run: pnpm install --global vercel@latest
      - run: vercel pull --yes --environment=preview --token=${{ secrets.VERCEL_TOKEN }}
      - run: vercel build --token=${{ secrets.VERCEL_TOKEN }}
      - run: |
          vercel deploy --prebuilt --token=${{ secrets.VERCEL_TOKEN }} | \
          xargs -I {} echo "DEPLOYMENT_URL={}" >> "${GITHUB_OUTPUT}"
        id: deployment
