name: Test

on:
  push:
  pull_request:
    branches: [master]
  workflow_dispatch:

jobs:
  test:
    name: Run Tests and Generate Coverage Report
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Setup pnpm
        uses: pnpm/action-setup@v3.0.0
        with:
          version: 8
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: "pnpm"
      - name: Cache Turborepo Tasks
        uses: actions/cache@v4
        with:
          path: ${{ github.workspace }}/node_modules/.cache/turbo
          key: ${{ runner.os }}-turbo-test-${{ hashFiles('**/pnpm-lock.yaml') }}
          restore-keys: ${{ runner.os }}-turbo-
      - run: pnpm install
      - run: pnpm lint
      - run: pnpm cov
